export const classes = [
  "AnimalTok",
  "ArtTok",
  "BeautyTok",
  "CookTok",
  "DanceTok",
  "FashionTok",
  "FitTok",
  "KidTok",
] as const
export type classesType = (typeof classes)[number][]
export const prompts = {
  BeautyTok: ["Makeup", "Skincare", "cosmetic products", "doing nails", "doing hair", "eyeshadow", "lipstick", "blush"],
  DanceTok: [
    "dance tutorial",
    "dance competition",
    "dance challenge",
    "dance trend",
    "dancing with friends",
    "dance class",
    "dance moves",
    "dance lessons",
    "dance choreography",
    "dance performances",
  ],
  CookTok: [
    "cooking tutorial",
    "cooking utensils ",
    "baking tutorials",
    "recipes",
    "restaurants",
    "food",
    "cooking utensils",
    "cooking tips",
    "cooking techniques",
    "healthy cooking",
  ],
  AnimalTok: ["dog", "cat", "birds", "fish ", "playing with pets", "fish", "feeding pets", "caring for animals"],
  KidTok: ["babies", "little girl", "little boy", "kids ", "toddlers", "children", "animation", "kid toys"],
  FashionTok: [
    "clothing",
    "outfit",
    "fashion design",
    "mens fashion",
    "womens fashion",
    "find your style",
    "upcoming fashion trends",
    "streetwear",
    "style advice",
  ],
  ArtTok: [
    "handicraft",
    "drawing",
    "graffiti",
    "sketching",
    "digital art",
    "sketchbook",
    "artists",
    "artwork",
    "painting",
  ],
  FitTok: [
    "doing exercises",
    "workout",
    "being active",
    "staying active",
    "personal trainer",
    "going to the gym",
    "weight training",
    "yoga",
  ],
} as const
